services:
  - type: web
    name: denoraa-ranking-api
    runtime: python
    pythonVersion: 3.11.9

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: MODEL_PATH
        value: denoraa_ranker_model.pkl
