services:
  - type: web
    name: denoraa-ranking-api
    runtime: python
    plan: free

    pythonVersion: "3.11"

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: MODEL_PATH
        value: denoraa_ranker_model.pkl
